# Builds a standalone harness from src/prism.cpp by EXTRACTING the real blocks.
# Nothing here is retyped: if a block cannot be found the generator fails loudly
# rather than silently testing a stale copy of the code.
#
#   cd /tmp && python3 <repo>/tools/prism-envelope-harness.py
#   g++ -std=c++11 -O1 -o h h.cpp
#   ./h 1     # retrigger step per preset -- the VCA discontinuity
#   ./h 2     # attack time vs one cycle of each partial's own frequency
#   ./h 0     # summed peak level per preset, against the +/-10V clamp
import re, sys, os
SRC = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'prism.cpp')).read()
OUT = os.getcwd()          # writes h.cpp beside you, not into tools/

def grab(pat, label, flags=re.S):
    m = re.search(pat, SRC, flags)
    if not m: sys.exit("EXTRACT FAILED: " + label)
    return m.group(0)

def between(start, end, label):
    a = SRC.find(start)
    if a < 0: sys.exit("EXTRACT FAILED (start): " + label)
    b = SRC.find(end, a)
    if b < 0: sys.exit("EXTRACT FAILED (end): " + label)
    return SRC[a:b+len(end)]

advance   = grab(r'static void advance\(float& e.*?\n\t\}\n', 'advance()')
defaultFor= grab(r'static float defaultFor\(int tab, int p\) \{.*?\n\t\}\n', 'defaultFor()')
initSpec  = grab(r'void initSpectrum\(\) \{.*?\n\t\}\n', 'initSpectrum()')
helpers   = between('static float knobTime(float k', 'static float cutKnob', 'helpers')
helpers   = helpers[:helpers.rfind('static float cutKnob')] + \
            grab(r'static float cutKnob\(float hz\) \{.*?\n\t\}\n', 'cutKnob')
loadpre   = grab(r'\tvoid loadPreset\(int which\) \{.*?\n\t\}\n(?=\n)', 'loadPreset()')
paramenum = grab(r'enum ParamId \{.*?\n\t\};', 'ParamId')
stage     = grab(r'enum Stage \{[^}]*\};', 'Stage')
moddest   = grab(r'enum PrModDest \{.*?PR_MOD_N \};', 'PrModDest')
consts    = "\n".join(grab(r'static const int %s[^\n]*\n' % c, c) for c in
                      ['PR_MAXP','PR_VOICES','PR_MODSRC','PR_NPRESET'])
# the level chain, exactly as the engine runs it
levelchain= between('float lv = pSoft[p] + (pLevel[p] - pSoft[p]) * morph;',
                    'lv *= envAmt;', 'level chain')
ratechain = between('float rateOwn = 0.25f * std::pow(16.f, pRate[p]);',
                    'float rateDie = rateOwn * (1.f + envRate * (float)p * 0.35f);', 'rate')

gateblk   = between('if (gate && !V.on) {', 'V.mRelFrom = std::max(V.mEnv, 1e-4f);\n\t\t\t}', 'gate block')

H = r'''
// GENERATED by gen.py -- every block below is lifted verbatim from prism.cpp.
#include <cmath>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <algorithm>
static float clamp(float v, float lo, float hi){ return v<lo?lo:(v>hi?hi:v); }
%(consts)s
%(moddest)s
static const char* PR_MODNAME[PR_MOD_N] = {"LVL","PIT","PAN","TLT","STR","CUT"};

struct P { float v=0.f; void setValue(float x){v=x;} float getValue()const{return v;} };

%(stage)s
struct Prism {
	%(paramenum)s
	P params[PARAMS_LEN];
	float pLevel[PR_MAXP]={}, pSoft[PR_MAXP]={}, pPitch[PR_MAXP]={};
	float pPan[PR_MAXP]={}, pDepth[PR_MAXP]={}, pRate[PR_MAXP]={};
	float mod[PR_MODSRC][PR_MOD_N]={};
	int nPartials = 16;

	%(defaultFor)s
	%(initSpec)s
	%(helpers)s
	%(loadpre)s
	%(advance)s
};

// The gate block reads the VEL input; give it one that reports 10V patched.
struct InStub { bool isConnected() const { return true; }
                float getVoltage(int=0) const { return 10.f; } };
static InStub gIn[4];
#define inputs gIn
static const int VEL_INPUT = 0;
static const int c = 0;

struct Voice {
	bool on=false; float vel=1.f;
	float env[PR_MAXP]={}; int stage[PR_MAXP]={}; float wait[PR_MAXP]={};
	float relFrom[PR_MAXP]={};
	float mEnv=0.f; int mStage=0; float mRelFrom=0.f;
};
// The REAL note-on / note-off block, lifted whole.
static void gateEdge(Voice& V, bool gate, int nPartials, float envSpr, float vel) {
	%(gateblk)s
}

static const char* NAME[PR_NPRESET] = {
	"Ramp","Square","CS-80","Marimba","Bell","Bowed","Bloom",
	"E-piano","Rotor","Clarinet","Gong","Vowel","Acid","Ensemble"};

// The level chain for ONE partial, verbatim, at a given envelope value.
static float levelOf(Prism& m, int p, float env, float morph,
                     float tilt, float oddEven, float envRate) {
	int n = p + 1;
	(void)envRate;
	float* pSoft = m.pSoft; float* pLevel = m.pLevel; float* pDepth = m.pDepth;
	float V_env_p = env;
	%(levelchain_body)s
	return lv;
}

int main(int argc, char** argv) {
	int mode = argc > 1 ? atoi(argv[1]) : 0;
	Prism m;

	if (mode == 2) {
		// ---- ATTACK: how long the VCA takes to open, and how that compares
		// with one cycle of a middle C. An attack much shorter than a cycle is
		// a step as far as the fundamental is concerned, however smooth the
		// envelope maths is. Also the FASTEST per-partial attack, because the
		// ENV RATE spread multiplies the attack as well as the decay.
		// Compared against EACH PARTIAL'S OWN cycle, which is the honest test:
		// a 0.5 ms attack is half a cycle for the fundamental but two and a half
		// for the sixteenth partial, and it is the partial that is opening.
		printf("preset      master A    worst partial: A / its own period\n");
		for (int i = 0; i < PR_NPRESET; i++) {
			m.loadPreset(i);
			float A  = 0.001f * std::pow(8000.f, m.params[Prism::ATTACK_PARAM].getValue());
			float worst = 1e9f; int wp = 0;
			for (int p = 0; p < m.nPartials; p++) {
				float rateOwn = 0.25f * std::pow(16.f, m.pRate[p]);
				float cyc = (A / rateOwn) * (float)(p + 1) * 261.6f;
				if (cyc < worst) { worst = cyc; wp = p + 1; }
			}
			printf("%%-10s  %%7.2f ms   %%6.2f cycles (partial %%2d)%%s\n",
			       NAME[i], A*1000.f, worst, wp,
			       worst < 0.5f ? "   <-- still a step" : "");
		}
	}
	else 	if (mode == 0) {
		// ---- PEAK SUM: what the summed partials reach before the output trim.
		printf("preset      np   sum|lv|   *1.6 trim   clipped at 10V?\n");
		for (int i = 0; i < PR_NPRESET; i++) {
			m.loadPreset(i);
			float tilt = m.params[Prism::TILT_PARAM].getValue();
			float oe   = m.params[Prism::ODDEVEN_PARAM].getValue();
			float er   = m.params[Prism::ENVRATE_PARAM].getValue();
			float sum = 0.f;
			for (int p = 0; p < m.nPartials; p++)
				sum += std::fabs(levelOf(m, p, 1.f, 1.f, tilt, oe, er));
			float peak = sum * 1.6f;
			printf("%%-10s %%3d   %%7.3f   %%9.2f V   %%s\n", NAME[i], m.nPartials,
			       sum, peak, peak > 10.f ? "YES -- HARD CLIP" : "no");
		}
	}
	else {
		// ---- RETRIGGER, through the REAL note-on block. Play 500 ms, release,
		// then 50 ms into the release retrigger. g = V.mEnv IS the VCA, so the
		// jump mEnv takes across the note-on is exactly the step the output
		// makes -- i.e. the click.
		printf("preset      VCA before   VCA after   STEP\n");
		const float dt = 1.f / 48000.f;
		float worst = 0.f;
		for (int i = 0; i < PR_NPRESET; i++) {
			m.loadPreset(i);
			float A = 0.001f * std::pow(8000.f, m.params[Prism::ATTACK_PARAM].getValue());
			float D = 0.005f * std::pow(2400.f, m.params[Prism::DECAY_PARAM].getValue());
			float S = m.params[Prism::SUSTAIN_PARAM].getValue();
			float R = 0.005f * std::pow(3200.f, m.params[Prism::RELEASE_PARAM].getValue());
			float spr = m.params[Prism::ENVSPREAD_PARAM].getValue();
			Voice V;
			gateEdge(V, true, m.nPartials, spr, 1.f);
			for (int k = 0; k < (int)(0.5f / dt); k++)
				Prism::advance(V.mEnv, V.mStage, V.mRelFrom, 1.f, 1.f, dt, A, D, S, R);
			gateEdge(V, false, m.nPartials, spr, 1.f);
			for (int k = 0; k < (int)(0.05f / dt); k++)
				Prism::advance(V.mEnv, V.mStage, V.mRelFrom, 1.f, 1.f, dt, A, D, S, R);
			float before = V.mEnv;
			gateEdge(V, true, m.nPartials, spr, 1.f);      // the retrigger
			float after = V.mEnv;
			float step = std::fabs(after - before);
			if (step > worst) worst = step;
			printf("%%-10s     %%6.4f      %%6.4f    %%6.4f%%s\n", NAME[i],
			       before, after, step, step > 0.01f ? "   <-- CLICK" : "");
		}
		printf("\nworst step across all presets: %%.4f  (1.0 = full scale)\n", worst);
	}
	return 0;
}
'''
# the level chain needs V.env[p] renamed to a plain local
lc = levelchain.replace('V.env[p]', 'V_env_p')
open(os.path.join(OUT,'h.cpp'),'w').write(H % dict(
    consts=consts, moddest=moddest, paramenum=paramenum, defaultFor=defaultFor,
    initSpec=initSpec, stage=stage, helpers=helpers, loadpre=loadpre, advance=advance, gateblk=gateblk,
    levelchain_body=lc))
print("generated; extracted %d blocks verbatim" % 9)
